import React from 'react'
import { SectionWrapper } from '../hoc'
import { motion } from 'framer-motion'
import { fadeIn } from '../utils/motion'
import { textVariant } from '../utils/motion'
import { jobs } from '../constants'
import { github } from '../assets'
import Tilt from 'react-tilt'